apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r8w7n0dxq-java-quarkus
  janus-idp.io/tekton: r8w7n0dxq-java-quarkus
  backstage.io/kubernetes-id: r8w7n0dxq-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r8w7n0dxq-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
